# Sakura
PRODUCT_VERSION_MAJOR = 10
PRODUCT_VERSION_MINOR = 0

# Increase Sakura Version with each major release.
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# Add time to filename if true
ifeq ($(LINEAGE_VERSION_APPEND_TIME_OF_DAY),true)
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif
LINEAGE_VERSION := ProjectSakura-$(LINEAGE_DISPLAY_VERSION)-$(LINEAGE_BUILD_DATE)-$(SAKURA_BUILD_ZIP_TYPE)-$(LINEAGE_BUILD)-$(SAKURA_BUILD)
SAKURA_VERSION := $(LINEAGE_VERSION)

PRODUCT_SYSTEM_PROPERTIES += \
    ro.lineage.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.modversion=$(SAKURA_VERSION)
